# Generated by Django 3.2.21 on 2023-09-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('apellido_paterno', models.CharField(blank=True, max_length=30)),
                ('apellido_materno', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('gender', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=9, verbose_name='género')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Téléfono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('image', models.ImageField(blank=True, upload_to='profile_pics', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='está activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es trabajador')),
                ('es_vendedor', models.BooleanField(default=False, verbose_name='es vendedor')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='es superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('celular', models.CharField(max_length=10)),
                ('correo_electronico', models.EmailField(max_length=250, null=True)),
                ('url_social', models.URLField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=13, null=True)),
                ('razon_social', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dato Fiscal',
                'verbose_name_plural': 'Datos Fiscales',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Dato Personal',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='DepartamentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('no_exterior', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilio',
            },
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedidaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=1)),
                ('datos_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.datoscontacto')),
                ('datos_personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.datospersonales')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('a', 'transferencia'), ('b', 'efectivo'), ('c', 'tarjeta de credito'), ('d', 'tarjeta de debito')], max_length=1)),
                ('importe_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vuelto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.cajas')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.clientes')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.usuariosacceso')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('existencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('existencia_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deparamento_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.departamentoproducto')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.datoscontacto')),
                ('datos_fiscales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.datosfiscales')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientosCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('a', 'abrir'), ('c', 'cerrar')], max_length=1)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.cajas')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.usuariosacceso')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.productos')),
                ('venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas_app.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
            },
        ),
        migrations.AddField(
            model_name='datosfiscales',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.domicilio'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='datos_contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.datoscontacto'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='datos_fiscales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas_app.datosfiscales'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='datos_personales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas_app.datospersonales'),
        ),
    ]
