# Generated by Django 4.2.4 on 2023-08-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
