# Generated by Django 4.2.4 on 2023-09-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='bodega',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='fecha_venta',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='material',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='stock',
        ),
    ]
