# Generated by Django 3.2.21 on 2023-10-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoscontacto',
            options={'verbose_name': 'Dato de Contacto', 'verbose_name_plural': 'Datos de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='departamentoproducto',
            options={'verbose_name': 'Departamento de Producto', 'verbose_name_plural': 'Departamentos de Productos'},
        ),
        migrations.AlterModelOptions(
            name='movimientoscaja',
            options={'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de Caja'},
        ),
        migrations.AlterModelOptions(
            name='negocio',
            options={'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
        migrations.AlterModelOptions(
            name='unidadesmedidaproducto',
            options={'verbose_name': 'Unidad de Medida de Producto', 'verbose_name_plural': 'Unidades de Medida de Productos'},
        ),
        migrations.AlterModelOptions(
            name='usuariosacceso',
            options={'verbose_name': 'Usuario de Acceso', 'verbose_name_plural': 'Usuarios de Acceso'},
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='descripcion',
            new_name='descripcion_marca',
        ),
    ]
