# Generated by Django 4.2.4 on 2023-08-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
