# Generated by Django 4.2.4 on 2023-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contrasenas',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Contraseña Actual'),
        ),
    ]
