# Generated by Django 4.2.4 on 2023-09-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_remove_marca_bodega_remove_marca_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password2',
        ),
    ]
