# Generated by Django 4.2.4 on 2023-08-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_usuario_apellido_materno_usuario_apellido_paterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrasenas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena_actual', models.CharField(max_length=50)),
                ('contrasena_nueva', models.CharField(max_length=50)),
                ('repetir_contrasena', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=9, verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Téléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Usuario'),
        ),
    ]
