# Generated by Django 4.2.4 on 2023-08-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0002_delete_contrasenas_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics', verbose_name='Imagen'),
        ),
    ]
