# Generated by Django 4.2.4 on 2023-08-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_contrasenas_alter_usuario_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='es_vendedor',
            field=models.BooleanField(default=False, verbose_name='es vendedor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='está activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='es trabajador'),
        ),
    ]
