# Generated by Django 4.2.4 on 2023-08-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0003_alter_usuario_gender_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
