# Generated by Django 4.2.4 on 2023-08-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0004_usuario_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Teléfono'),
        ),
    ]
